require("arnaiz.base")
require("arnaiz.plugins")
require("arnaiz.theme")
require("arnaiz.keybindings")

-- Plugins
require("arnaiz.cmp")
require("arnaiz.lsp")
require("arnaiz.indent")
require("arnaiz.treesitter")
require("arnaiz.lualine")
require("arnaiz.bufferline")
require("arnaiz.comment")
require("arnaiz.gitsigns")
require("arnaiz.nvim-ts-autotag")
require("arnaiz.noice")
require("arnaiz.notify")
require("arnaiz.lspsaga")
require("arnaiz.which-key")
require("arnaiz.web-devicons")
require("arnaiz.oil")
require("arnaiz.nvim-colorizer")
